export const ADD_CITY = "ADD_CITY";
export const REMOVE_CITY = "REMOVE_CITY";
export const SHOW_SUGGESTION_LIST = "SHOW_SUGGESTION_LIST";
export const REQUEST_IN_PROGRESS = "REQUEST_IN_PROGRESS";
export const REQUEST_FAILURE = "REQUEST_FAILURE";
