export const ADD_CITY = "ADD_CITY";
export const REMOVE_CITY = "REMOVE_CITY";
export const SHOW_SUGGESTION_LIST = "SHOW_SUGGESTION_LIST";
export const FETCH_DATA = "FETCH_DATA";
export const AN_ERROR_OCCURRED = "AN_ERROR_OCCURRED";
