version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:10.19.0
  environment:
    NODE_PATH: src/
  working_directory: ~/repo-

jobs:
  build-and-test:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: jest --coverage --runInBand
      # - store_artifacts:
      #     path: /home/circleci/project/coverage
      #       - run: npm test
      # - slack/status:
      #     fail_only: true
      #     only_for_branches: master
workflows:
  build-and-test:
    jobs:
      - build-and-test
